name: PizzaGuard
version: '1.0'
main: me.pizza.pizzaguard.PizzaGuard
api-version: '1.21'

commands:
  pizzaguard:
    usage: /pizzaguard <reload|debug>
    permission: pizzaguard.admin
  verify:
    usage: /verify <password>
    permission: pizzaguard.verify

permissions:
  pizzaguard.admin:
    default: op
  pizzaguard.verify:
    default: true